from pathlib import Path
from textwrap import wrap

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


OUTPUT_DIR = Path("certificates")


def draw_wrapped_text(
    pdf,
    text,
    x,
    y,
    max_chars=70,
    line_height=13
):
    """
    Draw long text across multiple lines.

    Returns the new y-position.
    """

    text = "" if text is None else str(text)

    lines = wrap(
        text,
        width=max_chars,
        break_long_words=True,
        break_on_hyphens=False
    )

    if not lines:
        lines = [""]

    for line in lines:
        pdf.drawString(x, y, line)
        y -= line_height

    return y


def draw_field(pdf, label, value, y, label_x=50, value_x=180):
    """
    Draw one labelled field and return the updated y-position.
    """

    value = "" if value is None else str(value)

    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(label_x, y, f"{label}:")

    pdf.setFont("Helvetica", 9)

    if len(value) > 70:
        y = draw_wrapped_text(
            pdf,
            value,
            value_x,
            y,
            max_chars=70,
            line_height=13
        )
        y -= 5
    else:
        pdf.drawString(value_x, y, value)
        y -= 18

    return y


def generate_certificate(record):
    """
    Generate a prototype electronic evidence record.

    IMPORTANT:
    This is a technical prototype document.
    It is not an official government certificate and does not,
    by itself, establish legal admissibility.
    """

    OUTPUT_DIR.mkdir(exist_ok=True)

    test_id = record.get("test_id", "UNKNOWN")

    output_file = OUTPUT_DIR / f"{test_id}_certificate.pdf"

    pdf = canvas.Canvas(
        str(output_file),
        pagesize=A4
    )

    width, height = A4

    # =========================================================
    # HEADER
    # =========================================================

    y = height - 50

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawCentredString(
        width / 2,
        y,
        "E-EVIDENCE RECORD"
    )

    y -= 22

    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawCentredString(
        width / 2,
        y,
        "DIGITAL TEST & EVIDENCE RECORD"
    )

    y -= 18

    pdf.setFont("Helvetica", 8)
    pdf.drawCentredString(
        width / 2,
        y,
        "Electronic Evidence Record — Prototype"
    )

    y -= 30

    # =========================================================
    # PART A — TEST RECORD
    # =========================================================

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, y, "PART A — TEST RECORD")

    y -= 25

    fields = [
        ("Test / Record ID", record.get("test_id")),
        ("Timestamp (UTC)", record.get("timestamp_utc")),
        ("Operator ID", record.get("operator_id")),
        ("Latitude", record.get("latitude")),
        ("Longitude", record.get("longitude")),
        ("Result", record.get("result")),
        ("Confidence", record.get("confidence")),
        ("Measurement", record.get("measurement")),
        ("Quality Status", record.get("quality_status")),
        ("Decision Reason", record.get("decision_reason")),
        ("Model Version", record.get("model_version")),
        ("Reference Version", record.get("reference_version")),
        ("Image SHA-256", record.get("image_sha256")),
        ("Record Hash", record.get("record_hash")),
        ("Hash Algorithm", "SHA-256"),
        ("Digital Signature", record.get("signature")),
        ("Signature Algorithm", "Ed25519"),
    ]

    for label, value in fields:

        # Start a new page if necessary
        if y < 100:
            pdf.showPage()

            y = height - 50

            pdf.setFont("Helvetica-Bold", 11)
            pdf.drawString(
                50,
                y,
                "E-EVIDENCE RECORD — CONTINUED"
            )

            y -= 30

        y = draw_field(
            pdf,
            label,
            value,
            y
        )

    # =========================================================
    # PART B — TECHNICAL SECURITY INFORMATION
    # =========================================================

    if y < 240:
        pdf.showPage()

        y = height - 50

        pdf.setFont("Helvetica-Bold", 11)
        pdf.drawString(
            50,
            y,
            "E-EVIDENCE RECORD — CONTINUED"
        )

        y -= 30

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(
        50,
        y,
        "PART B — TECHNICAL SECURITY INFORMATION"
    )

    y -= 25

    part_b_text = [
        "This document represents a technical electronic evidence",
        "record generated by the Digital Companion for Field Drug",
        "Testing prototype.",
        "",
        "The test record is stored using an encrypted SQLCipher",
        "database in the prototype implementation.",
        "",
        "The captured image can be represented by its SHA-256",
        "cryptographic digest.",
        "",
        "The complete canonical test record is hashed using SHA-256.",
        "",
        "The resulting record hash is digitally signed using Ed25519.",
        "",
        "The signed record includes security-relevant information",
        "such as the test identifier, UTC timestamp, operator ID,",
        "GPS coordinates, result, confidence, measurement, quality",
        "status, decision reason, model version, reference version",
        "and image SHA-256 value.",
        "",
        "Integrity verification consists of recalculating the record",
        "hash and verifying the Ed25519 signature.",
        "",
        "PROTOTYPE NOTICE:",
        "This document is a technical prototype generated for the",
        "Digital Companion for Field Drug Testing project.",
        "It is not an official government, forensic or NCB certificate.",
        "It must be reviewed against applicable legal requirements,",
        "approved procedures and the final deployment architecture",
        "before any real evidentiary use."
    ]

    pdf.setFont("Helvetica", 9)

    for line in part_b_text:

        if y < 70:
            pdf.showPage()

            y = height - 50

            pdf.setFont("Helvetica-Bold", 11)
            pdf.drawString(
                50,
                y,
                "E-EVIDENCE RECORD — CONTINUED"
            )

            y -= 30

            pdf.setFont("Helvetica", 9)

        pdf.drawString(50, y, line)

        y -= 13

    # =========================================================
    # FOOTER
    # =========================================================

    pdf.setFont("Helvetica", 7)

    pdf.drawCentredString(
        width / 2,
        30,
        "Digital Companion for Field Drug Testing — Prototype"
    )

    pdf.save()

    return str(output_file)